In [22]:
import pandas as pd
import re

In [23]:
original_df = pd.read_csv("../data/nyc_2024_data_selected.csv")
print(f"The data frame has {original_df.shape[0]} rows and {original_df.shape[1]} columns.")
# print(original_df.head())

The data frame has 30008 rows and 62 columns.

In [24]:
print(original_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 30008 entries, 0 to 30007
Data columns (total 62 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   property_id                                                      30008 non-null  int64
 1   primary_property_type_self                                       30008 non-null  str
 2   national_median_reference                                        29479 non-null  str
 3   list_of_all_property_use                                         30008 non-null  str
 4   largest_use_gfa_sqft                                             30001 non-null  float64
 5   _2nd_largest_property_use                                        8313 non-null   str
 6   second_use_gfa_sqft                                              8313 non-null   float64
 7   _3rd_largest_property_use                                        3252 non-null   str
 8   third_use_gfa_sqft                                               3252 non-null   float64
 9   year_built                                                       30008 non-null  int64
 10  number_of_buildings                                              30008 non-null  int64
 11  occupancy                                                        30008 non-null  int64
 12  metered_areas_water                                              21820 non-null  str
 13  site_eui_kbtu_ft                                                 29883 non-null  float64
 14  medical_office_gross_floor                                       938 non-null    float64
 15  medical_office_number_of                                         938 non-null    float64
 16  medical_office_number_of_1                                       938 non-null    float64
 17  medical_office_number_of_2                                       938 non-null    float64
 18  medical_office_percent_that                                      938 non-null    float64
 19  medical_office_percent_that_1                                    938 non-null    float64
 20  medical_office_weekly                                            938 non-null    float64
 21  k_12_school_gross_floor_area                                     1944 non-null   float64
 22  multifamily_housing_government                                   12010 non-null  str
 23  multifamily_housing_gross                                        20320 non-null  float64
 24  multifamily_housing_number                                       20318 non-null  float64
 25  multifamily_housing_number_1                                     20317 non-null  float64
 26  multifamily_housing_number_2                                     12120 non-null  float64
 27  multifamily_housing_number_3                                     12283 non-null  float64
 28  multifamily_housing_number_4                                     20318 non-null  float64
 29  multifamily_housing_percent                                      20318 non-null  float64
 30  multifamily_housing_percent_1                                    20318 non-null  float64
 31  multifamily_housing_total                                        20318 non-null  float64
 32  multifamily_housing_total_1                                      20317 non-null  float64
 33  multifamily_housing_number_5                                     20317 non-null  float64
 34  multifamily_housing_number_6                                     20318 non-null  float64
 35  multifamily_housing_number_7                                     20317 non-null  float64
 36  multifamily_housing_resident                                     11675 non-null  str
 37  office_gross_floor_area_ft                                       3556 non-null   float64
 38  office_number_of_computers                                       3556 non-null   float64
 39  office_number_of_workers                                         3555 non-null   float64
 40  office_percent_that_can_be                                       3555 non-null   float64
 41  office_percent_that_can_be_1                                     3554 non-null   float64
 42  office_weekly_operating_hours                                    3555 non-null   float64
 43  office_worker_density_number                                     3544 non-null   float64
 44  parking_open_parking_lot                                         3091 non-null   float64
 45  parking_completely_enclosed                                      3091 non-null   float64
 46  parking_partially_enclosed                                       3091 non-null   float64
 47  restaurant_gross_floor_area                                      1090 non-null   float64
 48  restaurant_weekly_operating                                      1090 non-null   float64
 49  restaurant_worker_density                                        1075 non-null   float64
 50  retail_store_gross_floor                                         2493 non-null   float64
 51  retail_store_number_of_walk                                      2493 non-null   float64
 52  retail_store_number_of_open                                      2493 non-null   float64
 53  property_gfa_self_reported                                       30008 non-null  float64
 54  electric_distribution_utility                                    29991 non-null  str
 55  number_of_active_energy_meters                                   30008 non-null  int64
 56  number_of_active_energy_meters_2                                 30008 non-null  int64
 57  number_of_active_it_meters                                       30008 non-null  int64
 58  aggregate_meter_s_electric_number_of_individual_meters_included  30008 non-null  int64
 59  borough                                                          28995 non-null  str
 60  latitude                                                         28991 non-null  float64
 61  longitude                                                        28991 non-null  float64
dtypes: float64(44), int64(8), str(10)
memory usage: 14.2 MB
None

***First, we drop the `property_id` column as it is not useful for a ML algorithm which is just used as an identifier.***

In [25]:
df = original_df.drop(columns=["property_id"])
# print(df.head())

In [26]:
print(df["metered_areas_water"].describe())
print("--------------------------------------------------")
print(df["electric_distribution_utility"].describe())

count              21820
unique                 5
top       Whole Property
freq               21795
Name: metered_areas_water, dtype: object
--------------------------------------------------
count                             29991
unique                                8
top       Consolidated Edison Co-NY Inc
freq                              29934
Name: electric_distribution_utility, dtype: object

***we drop the `national_median_reference` as it is just the nation-median category which overlaps the `primary_property_type_self`, drop the `list_of_all_property_use` is a very long string which is also overlaps with the other related columns such as `primary_property_type_self` and some gross columns, drop the `metered_areas_water` and `electric_distribution_utility` while most them are the same campany as listed above which is not useful for the training. Moreover, the `number_of_activate_energy_meters_2`, `number_of_active_it_meters`, and `aggregate_meter_s_electric_number_of_individual_meters_included` all overlap with the `number_of_active_energy_meters` whici is the total number of the meters. Plus, we also drop `_2nd_largest_property_use`, `second_use_gfa_sqft`, `_3rd_largest_property_use`, and `third_use_gfa_sqft` as they are considered redundant with the property-level sqft and have too much missing values.***

In [27]:
cols_to_drop = [
    "national_median_reference",
    "list_of_all_property_use",
    "metered_areas_water",
    "electric_distribution_utility",
    "number_of_active_energy_meters_2",
    "number_of_active_it_meters",
    "aggregate_meter_s_electric_number_of_individual_meters_included",
    "_2nd_largest_property_use",
    "second_use_gfa_sqft",
    "_3rd_largest_property_use",
    "third_use_gfa_sqft",
]

df = df.drop(columns=cols_to_drop)
print(df.shape)

(30008, 50)

***Here, as the target variable is the Site EUI which is the density measurement. To avoid overlapping, we drop the columns which means the total number of a property, just keep the density columns which is the same measurement from a different perspective.***

In [28]:
cols_to_drop = [
    "multifamily_housing_number",
    "multifamily_housing_total",
    "multifamily_housing_number_4",
    "multifamily_housing_number_6",
    "office_number_of_workers",
]

df = df.drop(columns=cols_to_drop)
print(df.shape)

(30008, 45)

***Since some of the data fields in the later sections of the dataset are specific to certain groups, we need to identify the records associated with different Property IDs within each group. Then, for each group, we check whether there are any missing values in the feature descriptions that are applicable to that particular group.***

In [29]:
property_types = {
    "Medical Office": "medical_office_",
    "K-12 School": "k_12_school_",
    "Multifamily Housing": "multifamily_housing_",
    "Office": "office_",
    "Restaurant": "restaurant_",
    "Parking": "parking_",
    "Retail Store": "retail_store_",
}

uses = original_df.loc[df.index, "list_of_all_property_use"]

property_groups = {}

for property_type in property_types:
    pattern = rf"(?:^|,\s*){re.escape(property_type)}\s*\("

    identifier = uses.str.contains(pattern, regex=True, na=False)

    property_groups[property_type] = df.loc[identifier].copy()

    print(f"{property_type} has {len(property_groups[property_type])} records.")

Medical Office has 938 records.
K-12 School has 1946 records.
Multifamily Housing has 20320 records.
Office has 3558 records.
Restaurant has 1090 records.
Parking has 3092 records.
Retail Store has 2495 records.

In [30]:
results = []

for property_type, group_df in property_groups.items():
    prefix = property_types[property_type]

    for col in group_df.columns:
        if col.startswith(prefix):
            results.append({
                "property_use": property_type,
                "feature": col,
                "num_of_records": len(group_df),
                "num_of_unique": group_df[col].nunique(),
                "missing_values_percent": group_df[col].isnull().mean() * 100,
            })

summary = pd.DataFrame(results)

display(summary.sort_values(["property_use", "missing_values_percent"], ascending=[True, False]).round(2))

,property_use,feature,num_of_records,num_of_unique,missing_values_percent
7,K-12 School,k_12_school_gross_floor_area,1946,1412,0.10
0,Medical Office,medical_office_gross_floor,938,745,0.00
1,Medical Office,medical_office_number_of,938,459,0.00
2,Medical Office,medical_office_number_of_1,938,8,0.00
3,Medical Office,medical_office_number_of_2,938,383,0.00
4,Medical Office,medical_office_percent_that,938,13,0.00
5,Medical Office,medical_office_percent_that_1,938,12,0.00
6,Medical Office,medical_office_weekly,938,82,0.00
18,Multifamily Housing,multifamily_housing_resident,20320,5,42.54
8,Multifamily Housing,multifamily_housing_government,20320,2,40.90
11,Multifamily Housing,multifamily_housing_number_2,20320,391,40.35
12,Multifamily Housing,multifamily_housing_number_3,20320,102,39.55
10,Multifamily Housing,multifamily_housing_number_1,20320,16361,0.01
15,Multifamily Housing,multifamily_housing_total_1,20320,16013,0.01
16,Multifamily Housing,multifamily_housing_number_5,20320,4497,0.01
17,Multifamily Housing,multifamily_housing_number_7,20320,10918,0.01
13,Multifamily Housing,multifamily_housing_percent,20320,24,0.01
14,Multifamily Housing,multifamily_housing_percent_1,20320,22,0.01
9,Multifamily Housing,multifamily_housing_gross,20320,15494,0.00
24,Office,office_worker_density_number,3558,2484,0.39
22,Office,office_percent_that_can_be_1,3558,53,0.11
21,Office,office_percent_that_can_be,3558,64,0.08
23,Office,office_weekly_operating_hours,3558,554,0.08
19,Office,office_gross_floor_area_ft,3558,3029,0.06
20,Office,office_number_of_computers,3558,1575,0.06
28,Parking,parking_open_parking_lot,3092,406,0.03
29,Parking,parking_completely_enclosed,3092,1779,0.03
30,Parking,parking_partially_enclosed,3092,187,0.03
27,Restaurant,restaurant_worker_density,1090,466,1.38
25,Restaurant,restaurant_gross_floor_area,1090,808,0.00
26,Restaurant,restaurant_weekly_operating,1090,114,0.00
31,Retail Store,retail_store_gross_floor,2495,1928,0.08
32,Retail Store,retail_store_number_of_walk,2495,17,0.08
33,Retail Store,retail_store_number_of_open,2495,45,0.08

***Deleting the missing values records, as we not want any missing values. If a record belongs to a particular group but its building features do not match the feature values associated with that group, we remove that record.***

In [31]:
df_clean = df.copy()

for property_type, group_df in property_groups.items():
    prefix = property_types[property_type]

    # find a corresponding column in this group
    group_cols = [
        col for col in group_df.columns
        if col.startswith(prefix)
    ]

    # find any missing value in this record
    missing_rows = group_df[group_df[group_cols].isnull().any(axis=1)]

    # drop it, the error="ignore" is to avoid KeyError if the index is not found in df_clean as there maybe some records belongs to multiple property_use
    df_clean = df_clean.drop(index=missing_rows.index, errors="ignore")

# drop if the target variable is missing
df_clean = df_clean.dropna(subset=["site_eui_kbtu_ft"])

print(df_clean.shape)

(19742, 45)

In [32]:
print(df_clean.columns.tolist())

['primary_property_type_self', 'largest_use_gfa_sqft', 'year_built', 'number_of_buildings', 'occupancy', 'site_eui_kbtu_ft', 'medical_office_gross_floor', 'medical_office_number_of', 'medical_office_number_of_1', 'medical_office_number_of_2', 'medical_office_percent_that', 'medical_office_percent_that_1', 'medical_office_weekly', 'k_12_school_gross_floor_area', 'multifamily_housing_government', 'multifamily_housing_gross', 'multifamily_housing_number_1', 'multifamily_housing_number_2', 'multifamily_housing_number_3', 'multifamily_housing_percent', 'multifamily_housing_percent_1', 'multifamily_housing_total_1', 'multifamily_housing_number_5', 'multifamily_housing_number_7', 'multifamily_housing_resident', 'office_gross_floor_area_ft', 'office_number_of_computers', 'office_percent_that_can_be', 'office_percent_that_can_be_1', 'office_weekly_operating_hours', 'office_worker_density_number', 'parking_open_parking_lot', 'parking_completely_enclosed', 'parking_partially_enclosed', 'restaurant_gross_floor_area', 'restaurant_weekly_operating', 'restaurant_worker_density', 'retail_store_gross_floor', 'retail_store_number_of_walk', 'retail_store_number_of_open', 'property_gfa_self_reported', 'number_of_active_energy_meters', 'borough', 'latitude', 'longitude']

In [33]:
print(df_clean["year_built"].max())

2025

In [34]:
print(df_clean.loc[df_clean["year_built"] == 2025])

      primary_property_type_self  largest_use_gfa_sqft  year_built  \
29516                     Office               47031.0        2025

       number_of_buildings  occupancy  site_eui_kbtu_ft  \
29516                    1          5               0.0

       medical_office_gross_floor  medical_office_number_of  \
29516                         NaN                       NaN

       medical_office_number_of_1  medical_office_number_of_2  ...  \
29516                         NaN                         NaN  ...

       restaurant_weekly_operating  restaurant_worker_density  \
29516                          NaN                        NaN

       retail_store_gross_floor  retail_store_number_of_walk  \
29516                       NaN                          NaN

      retail_store_number_of_open  property_gfa_self_reported  \
29516                         NaN                     58987.0

       number_of_active_energy_meters   borough   latitude  longitude
29516                               1  BROOKLYN  40.705394 -73.951875

[1 rows x 45 columns]

***Drop this column, as this record's `year_built` does not belong to 2024 and before.***

In [35]:
df_clean.drop(df_clean[df_clean["year_built"] == 2025].index, inplace=True)
print(df_clean.shape)

(19741, 45)

***Although there are some zero values in the `number_of_buildings` column, these zeros should not be treated as missing values because they have actual meaning. As shown in the displayed table, these records still contain valid values for our target variable and provide useful information. Therefore, we should retain these records rather than remove them.***

In [36]:
# print(df_clean["number_of_buildings"].describe())
# print(df_clean["number_of_buildings"].value_counts().sort_index().to_string())
print(df_clean["number_of_buildings"].isnull().sum())
display(df_clean.loc[df_clean["number_of_buildings"] == 0, ["primary_property_type_self", "largest_use_gfa_sqft", "property_gfa_self_reported", "number_of_buildings", "site_eui_kbtu_ft"]])

0

,primary_property_type_self,largest_use_gfa_sqft,property_gfa_self_reported,number_of_buildings,site_eui_kbtu_ft
868,K-12 School,24210.0,24210.0,0,44.3
936,K-12 School,38500.0,38500.0,0,167.4
1036,K-12 School,49510.0,49510.0,0,33.9
1037,K-12 School,51830.0,51830.0,0,52.0
1059,K-12 School,74400.0,74400.0,0,61.9
...,...,...,...,...,...
29549,Pre-school/Daycare,4500.0,4500.0,0,71.6
29550,Pre-school/Daycare,15000.0,15000.0,0,7.2
29551,College/University,74189.0,74189.0,0,96.0
29552,Other - Lodging/Residential,16000.0,16000.0,0,165.1
29960,Non-Refrigerated Warehouse,33171.0,33171.0,0,22.9

***Since our goal is to calculate the EUI for the entire site, we will retain `property_gfa_self_reported`. In contrast, `largest_use_gfa_sqft` only represents a portion of the site and therefore may not accurately reflect the characteristics of our target variable. As a result, we will drop the `largest_use_gfa_sqft` column.***

In [37]:
df_clean.drop(columns=["largest_use_gfa_sqft"], inplace=True)
print(df_clean.shape)

(19741, 44)

***We also noticed that many properties have a reported area of only 1 square foot, which is clearly unrealistic. These values can be considered outliers, as they may lead to significant deviations in our final predictions. Therefore, we removed these records to prevent unrealistic data from negatively affecting our model's performance.***

In [38]:
# print(df_clean["property_gfa_self_reported"].isnull().sum())
# print(df_clean.loc[df_clean["property_gfa_self_reported"] == 0])

In [39]:
# print(df_clean.loc[df_clean["property_gfa_self_reported"] == 1])
df_clean.drop(df_clean.loc[df_clean["property_gfa_self_reported"] == 1].index, inplace=True)
print(df_clean.shape)

(19737, 44)

***We also found that many records contain missing values for geographic information, including the regions where the properties are located and their latitude and longitude coordinates. Therefore, we removed all records with missing values in these demographic features.***

In [40]:
print(df_clean["borough"].isnull().sum())
print(df_clean["longitude"].isnull().sum())
print(df_clean["latitude"].isnull().sum())

683
686
686

In [41]:
df_clean.dropna(subset=["borough", "longitude", "latitude"], inplace=True)
print(df_clean.shape)

(19051, 44)

In [42]:
df_clean.to_csv("../data/nyc_2024_data_cleaned.csv", index=False)